--------------------------------------------------------
--  Fichier créé - mardi-novembre-02-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TABLE1
--------------------------------------------------------

  CREATE TABLE "CYRINE"."TABLE1" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"FONCTION" VARCHAR2(20 BYTE), 
	"SALAIRE" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"CIN_CHEF" NUMBER, 
	"CODE_P" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESTAURANT
--------------------------------------------------------

  CREATE TABLE "CYRINE"."RESTAURANT" 
   (	"ID_EMP" NUMBER, 
	"ID_CLIENT" NUMBER, 
	"CODE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"DATECOMMANDE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "CYRINE"."RESERVATION" 
   (	"CODE_RESERVATION" NUMBER, 
	"TYPE_RESERVATION" VARCHAR2(20 BYTE), 
	"NB_PERSSONE" VARCHAR2(20 BYTE), 
	"DATE_RESERVATION" VARCHAR2(20 BYTE), 
	"CIN_EMP" NUMBER, 
	"CIN_CL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARKING
--------------------------------------------------------

  CREATE TABLE "CYRINE"."PARKING" 
   (	"CODE" NUMBER, 
	"NOBRE_HEURE" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"CIN_EMP" NUMBER, 
	"CIN_CL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "CYRINE"."CLIENT" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"AGE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"E_MAIL" VARCHAR2(20 BYTE), 
	"NAISSANCE" VARCHAR2(20 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"NOMBRE_VISITE" VARCHAR2(20 BYTE), 
	"FIDELITE" VARCHAR2(20 BYTE), 
	"COLUMN2" VARCHAR2(20 BYTE), 
	"CODE_P" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CYRINE.TABLE1
SET DEFINE OFF;
REM INSERTING into CYRINE.RESTAURANT
SET DEFINE OFF;
REM INSERTING into CYRINE.RESERVATION
SET DEFINE OFF;
REM INSERTING into CYRINE.PARKING
SET DEFINE OFF;
REM INSERTING into CYRINE.CLIENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CIIN
--------------------------------------------------------

  CREATE UNIQUE INDEX "CYRINE"."CIIN" ON "CYRINE"."TABLE1" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESTAURANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CYRINE"."RESTAURANT_PK" ON "CYRINE"."RESTAURANT" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CYRINE"."RESERVATION_PK" ON "CYRINE"."RESERVATION" ("CODE_RESERVATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CODE_PARIKING
--------------------------------------------------------

  CREATE UNIQUE INDEX "CYRINE"."CODE_PARIKING" ON "CYRINE"."PARKING" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CIN_CLIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "CYRINE"."CIN_CLIENT" ON "CYRINE"."CLIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TABLE1
--------------------------------------------------------

  ALTER TABLE "CYRINE"."TABLE1" ADD CONSTRAINT "CIIN" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYRINE"."TABLE1" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESTAURANT
--------------------------------------------------------

  ALTER TABLE "CYRINE"."RESTAURANT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "CYRINE"."RESTAURANT" ADD CONSTRAINT "RESTAURANT_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYRINE"."RESTAURANT" MODIFY ("ID_EMP" NOT NULL ENABLE);
  ALTER TABLE "CYRINE"."RESTAURANT" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "CYRINE"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("CODE_RESERVATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYRINE"."RESERVATION" MODIFY ("CIN_CL" NOT NULL ENABLE);
  ALTER TABLE "CYRINE"."RESERVATION" MODIFY ("CIN_EMP" NOT NULL ENABLE);
  ALTER TABLE "CYRINE"."RESERVATION" MODIFY ("CODE_RESERVATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARKING
--------------------------------------------------------

  ALTER TABLE "CYRINE"."PARKING" MODIFY ("CIN_CL" NOT NULL ENABLE);
  ALTER TABLE "CYRINE"."PARKING" MODIFY ("CIN_EMP" NOT NULL ENABLE);
  ALTER TABLE "CYRINE"."PARKING" ADD CONSTRAINT "CODE_PARIKING" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "CYRINE"."CLIENT" ADD CONSTRAINT "CIN_CLIENT" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TABLE1
--------------------------------------------------------

  ALTER TABLE "CYRINE"."TABLE1" ADD CONSTRAINT "CIN_CHEF" FOREIGN KEY ("CIN_CHEF")
	  REFERENCES "CYRINE"."TABLE1" ("CIN") ENABLE;
  ALTER TABLE "CYRINE"."TABLE1" ADD CONSTRAINT "CODE_PARKING" FOREIGN KEY ("CODE_P")
	  REFERENCES "CYRINE"."PARKING" ("CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESTAURANT
--------------------------------------------------------

  ALTER TABLE "CYRINE"."RESTAURANT" ADD CONSTRAINT "CIN_CLIENTT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "CYRINE"."CLIENT" ("CIN") ENABLE;
  ALTER TABLE "CYRINE"."RESTAURANT" ADD CONSTRAINT "CIN_EMPLOYE" FOREIGN KEY ("ID_EMP")
	  REFERENCES "CYRINE"."TABLE1" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "CYRINE"."RESERVATION" ADD CONSTRAINT "CIN_CLIIENT" FOREIGN KEY ("CIN_CL")
	  REFERENCES "CYRINE"."CLIENT" ("CIN") ENABLE;
  ALTER TABLE "CYRINE"."RESERVATION" ADD CONSTRAINT "CIN_EMPLO" FOREIGN KEY ("CIN_EMP")
	  REFERENCES "CYRINE"."TABLE1" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARKING
--------------------------------------------------------

  ALTER TABLE "CYRINE"."PARKING" ADD CONSTRAINT "CIN_CLIENTTT" FOREIGN KEY ("CIN_CL")
	  REFERENCES "CYRINE"."CLIENT" ("CIN") ENABLE;
  ALTER TABLE "CYRINE"."PARKING" ADD CONSTRAINT "CIN_EMPLOYEE" FOREIGN KEY ("CIN_EMP")
	  REFERENCES "CYRINE"."TABLE1" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "CYRINE"."CLIENT" ADD CONSTRAINT "CODE_PARK" FOREIGN KEY ("CODE_P")
	  REFERENCES "CYRINE"."PARKING" ("CODE") ENABLE;
